---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart SSSD
  ansible.builtin.systemd_service:
    name: sssd
    state: restarted

- name: Force APT cache update
  ansible.builtin.apt:
    update_cache: true
